#
# Template for Web Builder, iMXRT1062
#

[platformio]
src_dir = src
include_dir = src

[common]
build_flags   =
  -I bluetooth # workaround for relative 3rd party plugin includes starting with ../
  -g3 
  -fmax-errors=5
  -fno-strict-aliasing
  -D OVERRIDE_MY_MACHINE

lib_archive   = no
lib_deps      = 
extra_scripts =
src_filter    = +<src/*>

[env]
framework     = arduino
extra_scripts = ${common.extra_scripts}
build_flags   = ${common.build_flags}
lib_deps      = ${common.lib_deps}
monitor_speed = 250000



[env:test]
board = teensy41
platform = teensy
board_build.f_cpu = 816000000L
build_flags = ${common.build_flags}
  -D WEB_BUILD
  -D BOARD_T41U5XBB
  -D USB_SERIAL_CDC=1
  -D PROBE_ENABLE=1
  -D FANS_ENABLE=1
  -D N_TOOLS=8
  -D ENABLE_JERK_ACCELERATION=1
  -D ACCELERATION_TICKS_PER_SECOND=400
  -D SEGMENT_BUFFER_SIZE=60
  -D ENABLE_ACCELERATION_PROFILES=1
  -D ENABLE_BACKLASH_COMPENSATION=1
  -D MINIMIZE_PROBE_OVERSHOOT=1
  -D CONTROL_ENABLE=70
  -D SPINDLE_ENABLE=2048

lib_deps = ${common.lib_deps}

